### ISSUE TITLE
Migrate to new repository

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-travis-build#2]
@jdubois :
I did a bad use of this repo :
- I worked only on master, so there is a history on every lib/binary
- the history become very big (on local, the size is approximatively 2go)
```shell
╭─pgrimaud@pgrimaud  ~/workspace/jhipster/jhipster-travis-build  ‹master› 
╰─$ du -h . --max-depth=1
603M	./node_modules
23M	./phantomjs
525M	./repository
340M	./node_modules_npm3
650M	./.git
2,1G	.
```
- so the Travis takes more and more time to clone this repo

Can you create for me a new repository in JHipster organization plz ? **jhipster-travis-cache** for example

What I plan to do:
- init the repo, the master will contain only README + LICENCE
- create branch from master, and upload lib
- when the lib in the branch is outdated, I will create a new one, upload new lib on it
- PR to generator-jhipster to point to this new branch
- then delete the old one

Thanks in advance! And **no** urgency

**Comment by jdubois** [comment]
I just created the repo and gave you write access.

**Comment by jdubois** [comment]
I'm closing this, just tell me when you want me to delete this repo...

**Comment by pascalgrimaud** [comment]
thanks @jdubois, I'll tell you
